apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: load-tester-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/VENKATESHWARAN-R/first-responder.git
    targetRevision: master
    path: application/frontend/my-app/k8s/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: load-tester
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
