apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: load-tester
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/VENKATESHWARAN-R/first-responder.git
    targetRevision: master
    path: infra/argocd/applications/load-tester
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
